### PR TITLE
README: Move badge immediately below title

### PR DESCRIPTION
**Pull request by rootulp**
For consistency with other languages

### CODE REVIEW

**Comment by petertseng** [comment]
confirming via `grep -C5 'travis-ci.org' ~/.gem/ruby/*/gems/trackler-*/tracks/*/README.md`

Above h1:

* C++

In h1:

* C
* Crystal
* ECMAScript
* Java
* Javascript
* Kotlin
* TypeScript

Between h1 and text:

* C#
* Delphi
* Elixir
* Elm
* F#
* Go
* Haskell
* Julia
* LFE
* Lua
* Nim
* Perl6
* PHP
* Pony
* Prolog
* Python
* Ruby
* Rust

Below text:

* Ceylon
* Lisp

Yeah, sure, Ceylon and Lisp are in the minority here. It'd be great if we can hear an argument for why the new placement is good. For example "all contributors have a uniform place to look for when looking for build status" (emphasising the consistency) or "the status image is more important than the introductory text, so the image should go above the text" (emphasising the position, without regard to consistency)

**Comment by rootulp** [comment]
By "Title" I was referring to the header tag `# xceylon`. I think the badge should be immediately below the title because, as you pointed out, the majority of other language tracks structure their READMEs like this. Consistency allows users to quickly parse a new Language's README for information. This is also how [Standard Readme](https://github.com/RichardLitt/standard-readme) suggests structuring the README.

**Comment by petertseng** [comment]
> immediately below

I'm going to have to edit both the commit message and PR title to say that, since otherwise it's a no-op (the badge is *already* below the title). As well as amend the explanation into the commit message, otherwise one won't be able to see the explanation without internet access

**Comment by petertseng** [comment]
Thanks!

**Pull request merged**
